/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.image;

import java.util.HashMap;
import javax.swing.JOptionPane;

/**
 *
 * @author MAIS
 */
public class MainFrame extends javax.swing.JFrame {
    HashMap<String, Integer> map = new HashMap<String, Integer>();
    private String []ask = {"HOW TO USE BOOLEAN EXPRESSION PROGRAM ","Write the boolean expression above        ",
    "Write the values for the variables you entered","Click over the Draw button to draw the cuircit"};
    private int idx = 0 ,i =1;
    /**
     * Creates new form NewJFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        redPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        expressionLabel = new javax.swing.JTextField();
        binaryText = new javax.swing.JTextField();
        calcButton = new javax.swing.JButton();
        rightButton = new javax.swing.JButton();
        leftButton = new javax.swing.JButton();
        askLabel = new javax.swing.JLabel();
        enterLabel = new javax.swing.JLabel();
        expressionText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mais's Program");
        setBackground(new java.awt.Color(255, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("AmdtSymbols", 0, 10)); // NOI18N

        redPanel.setBackground(new java.awt.Color(255, 255, 153));
        redPanel.setToolTipText("");

        titleLabel.setBackground(new java.awt.Color(153, 153, 0));
        titleLabel.setFont(new java.awt.Font("Gabriola", 1, 40)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(0, 0, 0));
        titleLabel.setText("Boolean Expression Program ");

        expressionLabel.setEditable(false);
        expressionLabel.setBackground(new java.awt.Color(255, 255, 153));
        expressionLabel.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        expressionLabel.setForeground(new java.awt.Color(0, 0, 0));
        expressionLabel.setText("Boolean Expression");
        expressionLabel.setBorder(null);
        expressionLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expressionLabelActionPerformed(evt);
            }
        });

        binaryText.setBackground(new java.awt.Color(153, 153, 153));
        binaryText.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        binaryText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                binaryTextActionPerformed(evt);
            }
        });

        calcButton.setBackground(new java.awt.Color(153, 153, 0));
        calcButton.setFont(new java.awt.Font("Footlight MT Light", 0, 18)); // NOI18N
        calcButton.setForeground(new java.awt.Color(0, 0, 0));
        calcButton.setText("Calculate");
        calcButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        calcButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcButtonActionPerformed(evt);
            }
        });

        rightButton.setText(">>");
        rightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightButtonActionPerformed(evt);
            }
        });

        leftButton.setText("<<");
        leftButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftButtonActionPerformed(evt);
            }
        });

        askLabel.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        askLabel.setForeground(new java.awt.Color(0, 0, 0));
        askLabel.setText("      HOW TO USE BOOLEAN EXPRESSION PROGRAM");

        enterLabel.setFont(new java.awt.Font("Gabriola", 0, 20)); // NOI18N
        enterLabel.setForeground(new java.awt.Color(0, 0, 0));
        enterLabel.setText("Enter the value of  the expression in binary Notation ");

        expressionText.setBackground(new java.awt.Color(153, 153, 153));
        expressionText.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        expressionText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expressionTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout redPanelLayout = new javax.swing.GroupLayout(redPanel);
        redPanel.setLayout(redPanelLayout);
        redPanelLayout.setHorizontalGroup(
            redPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(redPanelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(expressionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(redPanelLayout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addGroup(redPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enterLabel)
                    .addComponent(binaryText, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, redPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(leftButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(askLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, redPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(redPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, redPanelLayout.createSequentialGroup()
                        .addComponent(calcButton, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(211, 211, 211))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, redPanelLayout.createSequentialGroup()
                        .addComponent(titleLabel)
                        .addGap(78, 78, 78))))
            .addGroup(redPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(redPanelLayout.createSequentialGroup()
                    .addGap(223, 223, 223)
                    .addComponent(expressionText)
                    .addGap(45, 45, 45)))
        );
        redPanelLayout.setVerticalGroup(
            redPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(redPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(expressionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(enterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(binaryText, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(calcButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(redPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(leftButton)
                    .addComponent(rightButton)
                    .addComponent(askLabel))
                .addContainerGap())
            .addGroup(redPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(redPanelLayout.createSequentialGroup()
                    .addGap(110, 110, 110)
                    .addComponent(expressionText, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(317, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(redPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(redPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void leftButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftButtonActionPerformed
        // TODO add your handling code here:
        if(idx-1>=0){
            idx --;
            askLabel.setText(ask[idx]);
        } else{
            idx = 3 ;
            askLabel.setText(ask[idx]);
        }
    }//GEN-LAST:event_leftButtonActionPerformed

    private void rightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightButtonActionPerformed
        // TODO add your handling code here:
        if(idx+1<4){
            idx ++;
            askLabel.setText(ask[idx]);
        } else{
            idx = 0 ;
            askLabel.setText(ask[idx]);
        }
    }//GEN-LAST:event_rightButtonActionPerformed

    private void calcButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcButtonActionPerformed
        // TODO add your handling code here:
        DrawingAllFrame mais = new DrawingAllFrame(expressionText.getText(),binaryText.getText());
        mais.show();
        dispose();
        
    }//GEN-LAST:event_calcButtonActionPerformed

    private void binaryTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_binaryTextActionPerformed
        
    }//GEN-LAST:event_binaryTextActionPerformed

    private void expressionLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expressionLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expressionLabelActionPerformed

    private void expressionTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expressionTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expressionTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel askLabel;
    private javax.swing.JTextField binaryText;
    private javax.swing.JButton calcButton;
    private javax.swing.JLabel enterLabel;
    private javax.swing.JTextField expressionLabel;
    private javax.swing.JTextField expressionText;
    private javax.swing.JButton leftButton;
    private javax.swing.JPanel redPanel;
    private javax.swing.JButton rightButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
