/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.image;

/**
 *
 * @author MAIS
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        infoPanel = new javax.swing.JPanel();
        infoLabel = new javax.swing.JLabel();
        expressionL = new javax.swing.JLabel();
        expLabel = new javax.swing.JLabel();
        one = new javax.swing.JLabel();
        orGates = new javax.swing.JLabel();
        answerLabel = new javax.swing.JLabel();
        ans = new javax.swing.JLabel();
        andGates = new javax.swing.JLabel();
        two = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        infoPanel.setBackground(new java.awt.Color(255, 255, 153));

        infoLabel.setFont(new java.awt.Font("Gabriola", 1, 40)); // NOI18N
        infoLabel.setForeground(new java.awt.Color(0, 0, 0));
        infoLabel.setText("Information :");

        expressionL.setFont(new java.awt.Font("Gabriola", 0, 30)); // NOI18N
        expressionL.setForeground(new java.awt.Color(0, 0, 0));
        expressionL.setText("x+y");

        expLabel.setFont(new java.awt.Font("Gabriola", 0, 30)); // NOI18N
        expLabel.setForeground(new java.awt.Color(0, 0, 0));
        expLabel.setText("Expression with Variables :");

        one.setFont(new java.awt.Font("Gabriola", 0, 25)); // NOI18N
        one.setForeground(new java.awt.Color(0, 0, 0));
        one.setText("\" \"");

        orGates.setFont(new java.awt.Font("Gabriola", 0, 30)); // NOI18N
        orGates.setForeground(new java.awt.Color(204, 0, 0));
        orGates.setText("Number of OR gates \" + \"  = ");

        answerLabel.setFont(new java.awt.Font("Gabriola", 0, 30)); // NOI18N
        answerLabel.setForeground(new java.awt.Color(0, 0, 0));
        answerLabel.setText("Final Answer  = ");

        ans.setFont(new java.awt.Font("Gabriola", 0, 25)); // NOI18N
        ans.setForeground(new java.awt.Color(0, 0, 0));
        ans.setText("\" \"");

        andGates.setFont(new java.awt.Font("Gabriola", 0, 30)); // NOI18N
        andGates.setForeground(new java.awt.Color(0, 102, 0));
        andGates.setText("Number of AND gates \" . \"  = ");

        two.setFont(new java.awt.Font("Gabriola", 0, 25)); // NOI18N
        two.setForeground(new java.awt.Color(0, 0, 0));
        two.setText("\" \"");

        javax.swing.GroupLayout infoPanelLayout = new javax.swing.GroupLayout(infoPanel);
        infoPanel.setLayout(infoPanelLayout);
        infoPanelLayout.setHorizontalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(infoLabel)
                .addGap(113, 113, 113))
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(infoPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(answerLabel)
                        .addGap(18, 18, 18)
                        .addComponent(ans))
                    .addGroup(infoPanelLayout.createSequentialGroup()
                        .addComponent(orGates)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(two))
                    .addGroup(infoPanelLayout.createSequentialGroup()
                        .addComponent(andGates)
                        .addGap(18, 18, 18)
                        .addComponent(one))
                    .addComponent(expLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(infoPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(expressionL, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        infoPanelLayout.setVerticalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(infoLabel)
                .addGap(18, 18, 18)
                .addComponent(expLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(expressionL, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(answerLabel)
                    .addComponent(ans))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(one)
                    .addComponent(andGates))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(orGates)
                    .addComponent(two))
                .addContainerGap(155, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(infoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 141, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(infoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel andGates;
    private javax.swing.JLabel ans;
    private javax.swing.JLabel answerLabel;
    private javax.swing.JLabel expLabel;
    private javax.swing.JLabel expressionL;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JLabel one;
    private javax.swing.JLabel orGates;
    private javax.swing.JLabel two;
    // End of variables declaration//GEN-END:variables
}
